// lib/products.ts
export const products = [
  {
    id: 1,
    name: 'Round Neck',
    price: '₹449',
    color: 'Multi - Color',
    gsm: "180",
    piece: [{ name: '10 piece', inStock: true },
    { name: '20 piece', inStock: true },
    { name: 'Custom piece', inStock: true },],
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/tshirt.png',
    imageAlt: 'T-shirts laid out flat',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    id: 2,
    name: 'Round Neck',
    price: '₹449',
    gsm: "220",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/round-220.png',
    imageAlt: 'T-shirts laid out flat',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    id: 3,
    name: 'Oversized Tshirt',
    price: '₹449',
    gsm: "240",
    color: 'Black & White',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Black & White colors.',
    imageSrc: '/Oversized.png',
    imageAlt: 'Zip tote bag',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],

  },
  {
    id: 4,
    name: 'Oversized Tshirt',
    price: '₹449',
    gsm: "220",
    color: 'Black & White',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Black & White colors.',
    imageSrc: '/Oversized-200.jpg',
    imageAlt: 'Zip tote bag',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],

  },
  {
    id: 5,
    name: 'Collor T-shirt',
    price: '₹449',
    gsm: "220",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/collor-cotton.png',
    imageAlt: 'Zip tote bag',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },

  {
    id: 6,
    name: 'Collor T-shirt',
    price: '₹449',
    gsm: "250",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/typping.jpg',
    imageAlt: 'Zip tote bag',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    id: 7,
    name: 'Collor T-shirt',
    price: '₹449',
    gsm: "200",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/collor-Mars.png',
    imageAlt: 'Zip tote bag',
    highlights: [
      '✅ UV Protection & Antimicrobial ',
      '✅ Advanced Moisture Wicking ',
      '✅ Ultra Soft & Dri-Fit Comfort ',
      '✅ Crush Resistant & Color Fast',
      '✅ Temperature Neutralizing Design ',
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',
    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    id: 8,
    name: 'Hoodie',
    price: '₹449',
    gsm: "200",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/Hoodie.png',
    imageAlt: 'T-shirts laid out flat',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    id: 9,
    name: 'Sweat Shirts',
    price: '₹449',
    gsm: "200",
    color: 'Multi - Color',
    description: 'A pack of Minimum 10 to Maximum basic Tshirts in Multi colors.',
    imageSrc: '/Sweat.jpg',
    imageAlt: 'T-shirts laid out flat',
    highlights: [
      '✅ Free Delivery ',
      '✅ Free Customization',
      '✅ No Shipping Charges ',
      '✅ Within 24-hrs delivery ',

    ],
    piece: [{ name: '10 piece', inStock: true },
      { name: '20 piece', inStock: true },
      { name: 'Custom piece', inStock: true },],
    details: 'Engineered for performance, comfort, and durability, this tote adapts seamlessly to your lifestyle—whether you are at the office, on the field, or unwinding outdoors.',
    colors: [
      { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
      { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      { name: 'Multi-colour', class: 'bg-rainbow', selectedClass: 'ring-gray-900' },
      { name: 'Custom-colour', class: 'bg-red', selectedClass: 'ring-gray-900' },

    ],
    sizes: [
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },

  // {
  //   id: 10,
  //   name: 'Lycra - Track pant',
  //   price: '$92',
  //   color: 'Multi - Color',
  //   description: 'A pack of 6 basic tees in grayscale colors.',
  //   imageSrc: '/Track-Pant-2.png',
  //   imageAlt: 'T-shirts laid out flat',
  //   highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
  //   details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
  //   colors: [
  //       { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
  //       { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
  //     ],
  //     sizes: [
  //       { name: 'S', inStock: true },
  //       { name: 'M', inStock: true },
  //       { name: 'L', inStock: false },
  //       { name: 'XL', inStock: true },
  //     ],
  // },

  // {
  //   id: 8,
  //   name: 'Shorts',
  //   price: '$92',
  //   color: 'Multi - Color',
  //   description: 'A pack of 6 basic tees in grayscale colors.',
  //   imageSrc: '/shorts.png',
  //   imageAlt: 'T-shirts laid out flat',
  //   highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
  //   details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
  //  colors: [
  //       { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
  //       { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
  //     ],
  //     sizes: [
  //       { name: 'S', inStock: true },
  //       { name: 'M', inStock: true },
  //       { name: 'L', inStock: false },
  //       { name: 'XL', inStock: true },
  //     ],
  // },
  // Add more products as needed...
];
