// lib/products.ts
export const products = [
    {
      id: 1,
      name: 'Zip Tote Basket',
      price: '$140',
      color: 'White and black',
      description: 'A stylish zip tote bag in black and white.',
      imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: 'Zip tote bag',
      highlights: ['Durable material', 'Stylish design', 'Eco-friendly production'],
      details: 'This tote is made with durable canvas and features a classic black-and-white look.',
      colors: [
        { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
        { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      ],
      sizes: [
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
      ],
    },
    {
      id: 2,
      name: 'Basic Tee 6-Pack',
      price: '$192',
      color: 'Multicolor',
      description: 'A pack of 6 basic tees in grayscale colors.',
      imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
      imageAlt: 'T-shirts laid out flat',
      highlights: ['100% cotton', 'Pre-shrunk', 'Super soft fabric'],
      details: 'Includes two black, two white, and two heather gray Basic Tees.',
      colors: [
        { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
        { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      ],
      sizes: [
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
      ],
    },
    {
        id: 3,
        name: 'Zip Tote Basket',
        price: '$140',
        color: 'White and black',
        description: 'A stylish zip tote bag in black and white.',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
        imageAlt: 'Zip tote bag',
        highlights: ['Durable material', 'Stylish design', 'Eco-friendly production'],
        details: 'This tote is made with durable canvas and features a classic black-and-white look.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 4,
        name: 'Basic Tee 6-Pack',
        price: '$192',
        color: 'Multicolor',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['100% cotton', 'Pre-shrunk', 'Super soft fabric'],
        details: 'Includes two black, two white, and two heather gray Basic Tees.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 5,
        name: 'Zip Tote Basket',
        price: '$140',
        color: 'White and black',
        description: 'A stylish zip tote bag in black and white.',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
        imageAlt: 'Zip tote bag',
        highlights: ['Durable material', 'Stylish design', 'Eco-friendly production'],
        details: 'This tote is made with durable canvas and features a classic black-and-white look.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 6,
        name: 'Basic Tee 6-Pack',
        price: '$192',
        color: 'Multicolor',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['100% cotton', 'Pre-shrunk', 'Super soft fabric'],
        details: 'Includes two black, two white, and two heather gray Basic Tees.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
    // Add more products as needed...
  ];
  