// lib/products.ts
export const products = [
    {
      id: 1,
      name: 'Collor T-shirt',
      price: '$140',
      color: 'Multi - Color',
      description: 'A stylish zip tote bag in black and white.',
      imageSrc: '/collor-tshirt.png',
      imageAlt: 'Zip tote bag',
      highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
       colors: [
        { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
        { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      ],
      sizes: [
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
      ],
    },
    {
      id: 2,
      name: 'Plain  T-shirt',
      price: '$192',
      color: 'Multi - Color',
      description: 'A pack of 6 basic tees in grayscale colors.',
      imageSrc: '/tshirt.png',
      imageAlt: 'T-shirts laid out flat',
      highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
         colors: [
        { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
        { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
      ],
      sizes: [
        { name: 'S', inStock: true },
        { name: 'M', inStock: true },
        { name: 'L', inStock: false },
        { name: 'XL', inStock: true },
      ],
    },
    {
        id: 3,
        name: 'Collar Neck',
        price: '$10',
        color: 'Multi - Color',
        description: 'A stylish zip tote bag in black and white.',
        imageSrc: '/White-line-collor.png',
        imageAlt: 'Zip tote bag',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 4,
        name: 'Sports T-shirt',
        price: '$19',
        color: 'Multi - Color',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: '/Sports.png',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 5,
        name: 'Cotton Lycra Pant',
        price: '$40',
        color: 'Multi - Color',
        description: 'A stylish zip tote bag in black and white.',
        imageSrc: '/TrackPant1.png',
        imageAlt: 'Zip tote bag',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],       

      },
      {
        id: 6,
        name: 'Lycra - Track pant',
        price: '$92',
        color: 'Multi - Color',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: '/Track-Pant-2.png',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 7,
        name: 'Hoodie',
        price: '$92',
        color: 'Multi - Color',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: '/Hoodie.png',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
       colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
      {
        id: 8,
        name: 'Shorts',
        price: '$92',
        color: 'Multi - Color',
        description: 'A pack of 6 basic tees in grayscale colors.',
        imageSrc: '/shorts.png',
        imageAlt: 'T-shirts laid out flat',
        highlights: ['✅ UV Protection & Antimicrobial ', '✅ Advanced Moisture Wicking ', '✅ Ultra Soft & Dri-Fit Comfort ','✅ Crush Resistant & Color Fast','✅ Temperature Neutralizing Design '],
        details: 'This tote  is engineered for performance, comfort, and longevity. Whether you re at the office, on the field, or relaxing outdoors, this polo shirt adapts to your lifestyle.',
       colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
          sizes: [
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
          ],
      },
    // Add more products as needed...
  ];
  